# Pandas

- Data Analysis and Manipulation

- Fast 
- open Source

# installation
- pip install pandas

In [4]:
import pandas as pd
pd.__version__

'3.0.5'

In [ ]:
1. Series  - 1D 
2. DataFrame - 2D

# Series

In [8]:
a=[10,20,30,40,50]
myvar=pd.Series(a)
myvar

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [9]:
a=[10,20,30,40,50]
myvar=pd.Series(a,index=['a','b','c','d','e'])
myvar

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [11]:
a=(10,20,30,40,50)
myvar=pd.Series(a)
myvar

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [11]:
a=(10,20,30,40,50)
myvar=pd.Series(a,index=['a','b','c','d','e'])
myvar

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [12]:
a={"name":"Apple","color":"Red"}
myvar=pd.Series(a)
myvar

name     Apple
color      Red
dtype: str

In [14]:
a={"name":"Apple","color":"Red"}
myvar=pd.Series(a)
myvar.name="Fruits"
myvar

name     Apple
color      Red
Name: Fruits, dtype: str

# DataFrames - 2D

# Dataframe using List

In [16]:
suji=["Suji","Chennai","Da"]
vanu=["Vanu","Tanjai","Python"]
swe=["Swetha","Trichy","Java"]
student_details=[suji,vanu,swe]
df=pd.DataFrame(student_details)
df

        0        1       2
0    Suji  Chennai      Da
1    Vanu   Tanjai  Python
2  Swetha   Trichy    Java

In [18]:
suji=("Suji","Chennai","Da")
vanu=("Vanu","Tanjai","Python")
swe=("Swetha","Trichy","Java")
thiru=("thiru","Salem","AI/Ml")
student_details=[suji,vanu,swe,thiru]
df=pd.DataFrame(student_details)
df

        0        1       2
0    Suji  Chennai      Da
1    Vanu   Tanjai  Python
2  Swetha   Trichy    Java
3   thiru    Salem   AI/Ml

# Data frames Using Dictionary

In [20]:
fruits={
    "fruits":['apple','orange','banana'],
    "color":["red","orange","yellow"],
    "price":[100,200,300]
}
df=pd.DataFrame(fruits)
df

   fruits   color  price
0   apple     red    100
1  orange  orange    200
2  banana  yellow    300