In [1]:
import pandas as pd

In [2]:
df1=pd.DataFrame([[1,5,9],[5,2,10],[30,90,2]])
df1.columns=['A','B','C']
df1

    A   B   C
0   1   5   9
1   5   2  10
2  30  90   2

In [3]:
df2=pd.DataFrame([[9,10,5,2],[1,2,3,4],[9,7,4,1],[3,6,6,4]])
df2.columns=['C','D','E','F']
df2

   C   D  E  F
0  9  10  5  2
1  1   2  3  4
2  9   7  4  1
3  3   6  6  4

In [4]:
# Align Based on Column Value
# align - left,right,inner,outer

In [5]:
left, right=df1.align(df2,join='left')

In [6]:
left

    A   B   C
0   1   5   9
1   5   2  10
2  30  90   2

In [7]:
right

    A   B  C
0 NaN NaN  9
1 NaN NaN  1
2 NaN NaN  9

In [8]:
left, right=df1.align(df2,join='left',axis=0)

In [9]:
left

    A   B   C
0   1   5   9
1   5   2  10
2  30  90   2

In [10]:
right

   C   D  E  F
0  9  10  5  2
1  1   2  3  4
2  9   7  4  1

In [11]:
left, right=df1.align(df2,join='right')

In [12]:
left

      C   D   E   F
0   9.0 NaN NaN NaN
1  10.0 NaN NaN NaN
2   2.0 NaN NaN NaN
3   NaN NaN NaN NaN

In [13]:
right

   C   D  E  F
0  9  10  5  2
1  1   2  3  4
2  9   7  4  1
3  3   6  6  4

In [14]:
left, right=df1.align(df2,join='inner')

In [15]:
left

    C
0   9
1  10
2   2

In [16]:
right

   C
0  9
1  1
2  9

In [17]:
left, right=df1.align(df2,join='outer')
left

      A     B     C   D   E   F
0   1.0   5.0   9.0 NaN NaN NaN
1   5.0   2.0  10.0 NaN NaN NaN
2  30.0  90.0   2.0 NaN NaN NaN
3   NaN   NaN   NaN NaN NaN NaN

In [18]:
right

    A   B  C   D  E  F
0 NaN NaN  9  10  5  2
1 NaN NaN  1   2  3  4
2 NaN NaN  9   7  4  1
3 NaN NaN  3   6  6  4