In [1]:
import pandas as pd

In [2]:
fruits=['Apple','Orange','Banana']
Color=['Red','orange','Yellow']
price=[100,200,300]
basket=zip(fruits,Color,price)
df=pd.DataFrame(basket)
df.columns=["Fruits","Color","Price"]
df

   Fruits   Color  Price
0   Apple     Red    100
1  Orange  orange    200
2  Banana  Yellow    300

In [4]:
df.ndim

2

In [6]:
df['Fruits'].ndim

1

In [9]:
df.dtypes

Fruits      str
Color       str
Price     int64
dtype: object

In [10]:
df['Fruits'].dtypes

In [11]:
df.memory_usage()

Index     132
Fruits     24
Color      24
Price      24
dtype: int64

In [13]:
df.memory_usage(deep=True)

Index     132
Fruits    164
Color     162
Price      24
dtype: int64

In [32]:
df=pd.read_csv("../../../data.csv")
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [15]:
df.dtypes

Duration      int64
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [16]:
df.memory_usage(deep=True)

Index        132
Duration    1352
Pulse       1352
Maxpulse    1352
Calories    1352
dtype: int64

In [23]:
df['Calories']=df['Calories'].astype('float16')

In [31]:
df.columns.to_list()

['Fruits', 'Color', 'Price']

In [35]:
df=df.astype(
    {
        "Pulse":"int8",
        "Maxpulse":"int8"
     }
)

In [36]:
df.memory_usage(deep=True)

Index        132
Duration    1352
Pulse        169
Maxpulse     169
Calories    1352
dtype: int64

In [25]:
fruits=['Apple','Orange','Banana']
Color=['Red','orange','Yellow']
price=[100,200,300]
basket=zip(fruits,Color,price)
df=pd.DataFrame(basket)
df.columns=["Fruits","Color","Price"]
df

   Fruits   Color  Price
0   Apple     Red    100
1  Orange  orange    200
2  Banana  Yellow    300

In [27]:
df.memory_usage()

Index     132
Fruits     24
Color      24
Price      24
dtype: int64

In [28]:
df.memory_usage(deep=True)

Index     132
Fruits    164
Color     162
Price      24
dtype: int64