In [1]:
import pandas as pd

In [5]:
# concat join Vertical
# pd.concat([df1,df2])

In [3]:
df1=pd.DataFrame(
    [
        [1,5],
        [5,2]
    ]
)
df1.columns=['A','B']
df1

   A  B
0  1  5
1  5  2

In [4]:
df2=pd.DataFrame([
    [12,5],
    [1,4]
])
df2.columns=['A','B']
df2

    A  B
0  12  5
1   1  4

In [6]:
df3=pd.DataFrame(
    [[12,5],
    [1,4]]
)
df3.columns=['B','C']
df3

    B  C
0  12  5
1   1  4

In [9]:
pd.concat([df1,df2])

    A  B
0   1  5
1   5  2
0  12  5
1   1  4

In [10]:
pd.concat([df1,df3])

     A   B    C
0  1.0   5  NaN
1  5.0   2  NaN
0  NaN  12  5.0
1  NaN   1  4.0

In [7]:
# Joining with Various Column Names (horizonal)
# df1.join(df2,lsuffix="_one",rsuffix="_two")

In [11]:
df1.join(df2)

ValueError: columns overlap but no suffix specified: Index(['A', 'B'], dtype='str')

In [13]:
df1.join(df2,lsuffix="_one",rsuffix="_two")

   A_one  B_one  A_two  B_two
0      1      5     12      5
1      5      2      1      4