In [1]:
import pandas as pd

- df['origin'].unique()
- df['origin'].value_counts()
- Find Duplicates: df.duplicated().sum()
- Remove: df.drop_duplicates().head()
## Ranking
- df.nlargest(3,'weight')
- df_head.nsmallest(4,'Displacement')
## Ranking Row 
- df_head['Rank']=df_head['Accelarate'].rank(method='first')
- method=> min,max,dense,first
- df_head[df_head['Rank']<=3]

# Statistical Analysis
1. df['weight'].skew()
2. df['weight'].kurt() 
3. Data distributed across dataset : 
## 50% of data Distribution
df['weight'].quantile()
4. Ranking: df_head.nlargest(3,'weight')

# Relationship Analysis
## 1. Covariance - how one Variable move with Other Variable in terms of Direction(Covariance → direction)
- height incr -> weight incr => Positive
- height incr -> weight decr => Negative
- df['Horsepower'].cov(df['weight'])
## 2. Correlation → direction + strength
- df['Horsepower'].corr(df['weight'])*100

In [2]:
df=pd.read_csv('../../../car_data_500.csv').head()
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [3]:
df['origin'].unique()

<StringArray>
['Japan', 'US', 'India', 'Germany']
Length: 4, dtype: str

In [4]:
df['Cylinder'].unique()

array([6., 4., 8.])

In [5]:
df['Cylinder'].nunique()

3

In [6]:
df['origin'].nunique()

4

In [11]:
df.loc[df['origin'].duplicated()]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [13]:
df['origin'].drop_duplicates()

0      Japan
1         US
2      India
3    Germany
Name: origin, dtype: str

In [14]:
df.nlargest(3,'weight')

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany

In [15]:
df.nsmallest(3,'weight')

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany

In [18]:
df['Rank']=df['Accelarate'].rank(method='first')
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,Rank
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,4.0
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,5.0
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,2.0
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,3.0
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,1.0

In [19]:
df['Rank']=df['Cylinder'].rank(method='first')
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,Rank
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,2.0
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,1.0
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,5.0
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,3.0
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,4.0

In [20]:
df['Rank']=df['Cylinder'].rank(method='min')
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,Rank
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,2.0
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,1.0
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,5.0
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,2.0
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,2.0

In [21]:
df['Rank']=df['Cylinder'].rank(method='max')
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,Rank
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,4.0
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,1.0
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,5.0
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,4.0
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,4.0

In [22]:
df['Rank']=df['Cylinder'].rank(method='dense')
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,Rank
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,2.0
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,1.0
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,3.0
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,2.0
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,2.0

In [23]:
df['weight'].skew()

np.float64(-0.9671008294148353)

In [24]:
df['weight'].quantile()

np.float64(3317.0)

In [25]:
df['weight'].quantile(.25)

np.float64(2706.0)