In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('../../../car_data_500.csv').head()
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [4]:
df.drop([1,2,3],axis=0)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [5]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [6]:
df.drop([1,2],axis=0,inplace=True)

In [7]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [8]:
df.drop(['Model','origin'],axis=1)

       car   MPO  Cylinder  Displacement  Horsepower  weight  Accelarate
0     Ford  20.7       6.0          1823         247    3374        15.5
3  Hyundai  11.5       6.0          4498         196    3317         9.9
4     Tata  18.0       6.0          2968         140    2706         7.2

In [9]:
df.drop(columns=['MPO'])

,car,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,6.0,1823,247,3374,15.5,76,Japan
3,Hyundai,6.0,4498,196,3317,9.9,77,Germany
4,Tata,6.0,2968,140,2706,7.2,74,US

In [10]:
# pop

In [11]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [15]:
df

,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,20.7,6.0,1823,247,3374,15.5,76,Japan
3,11.5,6.0,4498,196,3317,9.9,77,Germany
4,18.0,6.0,2968,140,2706,7.2,74,US

In [16]:
Cylinder=df.pop('Cylinder')

In [18]:
Cylinder

0    6.0
3    6.0
4    6.0
Name: Cylinder, dtype: float64

In [19]:
df

    MPO  Displacement  Horsepower  weight  Accelarate  Model   origin
0  20.7          1823         247    3374        15.5     76    Japan
3  11.5          4498         196    3317         9.9     77  Germany
4  18.0          2968         140    2706         7.2     74       US

In [24]:
df.truncate(0,3,axis=0)

    MPO  Displacement  Horsepower  weight  Accelarate  Model   origin
0  20.7          1823         247    3374        15.5     76    Japan
3  11.5          4498         196    3317         9.9     77  Germany

In [25]:
df

    MPO  Displacement  Horsepower  weight  Accelarate  Model   origin
0  20.7          1823         247    3374        15.5     76    Japan
3  11.5          4498         196    3317         9.9     77  Germany
4  18.0          2968         140    2706         7.2     74       US

In [26]:
df.truncate("MPO","Displacement",axis=1)

ValueError: truncate requires a sorted index

In [31]:
df=df.sort_index(axis=1)

In [32]:
df

   Accelarate  Displacement  Horsepower   MPO  Model   origin  weight
0        15.5          1823         247  20.7     76    Japan    3374
3         9.9          4498         196  11.5     77  Germany    3317
4         7.2          2968         140  18.0     74       US    2706

In [33]:
df.truncate("MPO","Displacement",axis=1)

ValueError: Truncate: Displacement must be after MPO

In [34]:
df.truncate("MPO","Model",axis=1)

    MPO  Model
0  20.7     76
3  11.5     77
4  18.0     74