In [1]:
import pandas as pd

In [3]:
df_filter=pd.read_csv('../../../car_data_500.csv').head(10)
df_filter

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US
5,Kia,15.7,6.0,2659,155,3156,10.2,76,US
6,Toyota,16.9,8.0,3148,102,3974,15.5,79,South Korea
7,Ford,19.1,8.0,4693,150,1800,12.7,72,South Korea
8,BMW,17.5,6.0,3801,221,1818,10.8,76,South Korea
9,Tata,18.1,6.0,3268,130,2383,11.1,80,India

In [5]:
df_filter['Horsepower']>200

0     True
1    False
2     True
3    False
4    False
5    False
6    False
7    False
8     True
9    False
Name: Horsepower, dtype: bool

In [6]:
df_filter[df_filter['Horsepower']>200]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
8,BMW,17.5,6.0,3801,221,1818,10.8,76,South Korea

In [7]:
df_filter.loc[df_filter['Horsepower']>200]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
8,BMW,17.5,6.0,3801,221,1818,10.8,76,South Korea

In [8]:
df_filter.loc[df_filter['origin']=="us"]

Empty DataFrame
Columns: [car, MPO, Cylinder, Displacement, Horsepower, weight, Accelarate, Model, origin]
Index: []

In [9]:
df_filter.loc[df_filter['origin'].str.lower() =="us"]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US
5,Kia,15.7,6.0,2659,155,3156,10.2,76,US

In [10]:
df_filter.filter(items=[1,2,4,5],axis=0)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US
5,Kia,15.7,6.0,2659,155,3156,10.2,76,US

In [11]:
df_filter.filter(items=['car','Cylinder'],axis=1)

       car  Cylinder
0     Ford       6.0
1   Jaguar       4.0
2     Audi       8.0
3  Hyundai       6.0
4     Tata       6.0
5      Kia       6.0
6   Toyota       8.0
7     Ford       8.0
8      BMW       6.0
9     Tata       6.0

In [12]:
df_filter['origin']=="South Korea"

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9    False
Name: origin, dtype: bool

In [16]:
df_filter[df_filter['origin']=="South Korea"][['car','Model']]

      car  Model
6  Toyota     79
7    Ford     72
8     BMW     76