In [1]:
import pandas as pd

# Function

In [2]:
df=pd.read_csv('../../../car_data_500.csv').head()

In [3]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

# On Series

In [7]:
# Custom Function

In [11]:
def convert_values(word:str): # we can only apply only one Parameter
    return word.lower().replace(' ','');

In [12]:
convert_values('Hello World')

'helloworld'

In [13]:
df['car'].apply(convert_values)

0       ford
1     jaguar
2       audi
3    hyundai
4       tata
Name: car, dtype: str

# on DataFrame

In [14]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

# custom Function

In [20]:
def convert_function(column:pd.Series):
    return column.str.lower()

In [17]:
df_str=df[['car','origin']]

In [18]:
df_str

       car   origin
0     Ford    Japan
1   Jaguar       US
2     Audi    India
3  Hyundai  Germany
4     Tata       US

In [19]:
df_str.apply(convert_function)

       car   origin
0     ford    japan
1   jaguar       us
2     audi    india
3  hyundai  germany
4     tata       us

In [21]:
def convert_function(column:pd.Series):
    return column.str.lower().str.replace(' ','')

In [22]:
df_str.apply(convert_function)

       car   origin
0     ford    japan
1   jaguar       us
2     audi    india
3  hyundai  germany
4     tata       us

# Assign Function on DataFrame

In [24]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [ ]:
# weight (kg - tonnes)
# Horsepower(hp-k.watt)

In [26]:
def convert_kg_to_tonnes(weigth_kg):
    return weigth_kg/1000

def convert_hp_to_kw(hp):
    return hp*0.745

In [29]:
df.assign(tonnes=convert_kg_to_tonnes(df['weight'])) # if we give exsisting name its overwrite the original

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,tonnes
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,3.374
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,2.196
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,3.527
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,3.317
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,2.706

In [30]:
df.assign(tonnes=convert_kg_to_tonnes(df['weight']),
         kw=convert_hp_to_kw(df['Horsepower']))

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,tonnes,kw
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,3.374,184.015
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,2.196,138.570
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,3.527,197.425
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,3.317,146.020
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,2.706,104.300

In [33]:
df_transform=df.assign(weight=convert_kg_to_tonnes(df['weight']),
         Horsepower=convert_hp_to_kw(df['Horsepower']))

In [34]:
df_transform

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,184.015,3.374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,138.570,2.196,15.9,73,US
2,Audi,21.3,8.0,1943,197.425,3.527,8.3,80,India
3,Hyundai,11.5,6.0,4498,146.020,3.317,9.9,77,Germany
4,Tata,18.0,6.0,2968,104.300,2.706,7.2,74,US

# Aggregate Functions on Series

In [36]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [37]:
# sum and Product

In [38]:
df['weight'].sum()

np.int64(15120)

In [41]:
df['weight'].product()

np.int64(234561179849196816)

In [40]:
df['weight'].prod()

np.int64(234561179849196816)

In [42]:
# mean => Average
# median => center Value

In [43]:
df['weight'].mean()

np.float64(3024.0)

In [44]:
df['weight'].median()

np.float64(3317.0)

In [45]:
df['weight'].min()

np.int64(2196)

In [46]:
df['weight'].max()

np.int64(3527)

In [47]:
df['weight'].count() # dont cont missing Value

np.int64(5)

In [50]:
df['Horsepower'].size # cont missing Value too

5

In [51]:
df['Horsepower'].std()

np.float64(50.03698632012124)

In [52]:
df['Horsepower'].var()

np.float64(2503.7)

# Aggregate Functions on DataFrame

In [54]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [55]:
df.sum()  # string concat , number add

car             FordJaguarAudiHyundaiTata
MPO                                  88.9
Cylinder                             30.0
Displacement                        13025
Horsepower                           1034
weight                              15120
Accelarate                           56.8
Model                                 380
origin              JapanUSIndiaGermanyUS
dtype: object

In [56]:
df.sum(numeric_only=True)

MPO                88.9
Cylinder           30.0
Displacement    13025.0
Horsepower       1034.0
weight          15120.0
Accelarate         56.8
Model             380.0
dtype: float64

In [57]:
df.max(numeric_only=True)

MPO               21.3
Cylinder           8.0
Displacement    4498.0
Horsepower       265.0
weight          3527.0
Accelarate        15.9
Model             80.0
dtype: float64

In [59]:
# Group by Function

In [60]:
## 1. Find Maximum Weight Based on Origin

In [65]:
df['weight'].max()

np.int64(3527)

In [66]:
df['weight'].groupby(df['origin']).max()

origin
Germany    3317
India      3527
Japan      3374
US         2706
Name: weight, dtype: int64

In [67]:
df.groupby('origin').max()

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model
origin,,,,,,,,
Germany,Hyundai,11.5,6.0,4498,196,3317,9.9,77
India,Audi,21.3,8.0,1943,265,3527,8.3,80
Japan,Ford,20.7,6.0,1823,247,3374,15.5,76
US,Tata,18.0,6.0,2968,186,2706,15.9,74

In [68]:
df.groupby('origin').max(numeric_only=True)

          MPO  Cylinder  Displacement  Horsepower  weight  Accelarate  Model
origin
Germany  11.5       6.0          4498         196    3317         9.9     77
India    21.3       8.0          1943         265    3527         8.3     80
Japan    20.7       6.0          1823         247    3374        15.5     76
US       18.0       6.0          2968         186    2706        15.9     74

In [69]:
df.groupby('origin')['weight'].max(numeric_only=True)

origin
Germany    3317
India      3527
Japan      3374
US         2706
Name: weight, dtype: int64

In [61]:
## 2. Find Maximum Weight Based on Cylinder

In [70]:
df.groupby('Cylinder')['weight'].max()

Cylinder
4.0    2196
6.0    3374
8.0    3527
Name: weight, dtype: int64

In [62]:
## 3. Find Maximum Displacement Based on Cylinder

In [71]:
df.groupby('Cylinder')['Displacement'].max()

Cylinder
4.0    1793
6.0    4498
8.0    1943
Name: Displacement, dtype: int64

In [63]:
## 4. Find MAximum  Weight Based on Both Origin & Cylinder

In [72]:
df.groupby(['origin','Cylinder'])['weight'].max()

origin   Cylinder
Germany  6.0         3317
India    8.0         3527
Japan    6.0         3374
US       4.0         2196
         6.0         2706
Name: weight, dtype: int64

In [64]:
## 5. Find Maximum Weight & Displacement Based on Both Origin & Cylinder

In [77]:
df.groupby(['origin','Cylinder'])[['weight','Displacement']].max()

                  weight  Displacement
origin  Cylinder
Germany 6.0         3317          4498
India   8.0         3527          1943
Japan   6.0         3374          1823
US      4.0         2196          1793
        6.0         2706          2968

# Transform

In [79]:
# 1. Add Column for Maximum Weight

In [81]:
df['weight'].max()

np.int64(3527)

In [83]:
df['MaxWeight']=df['weight'].max()
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,MaxWeight
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,3527
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,3527
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,3527
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,3527
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,3527

In [ ]:
# 2. Add maximum weight based on Region

In [84]:
df['origin_Max_weight']=df.groupby('origin')['weight'].transform('max')

In [85]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,MaxWeight,origin_Max_weight
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,3527,3374
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,3527,2706
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,3527,3527
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,3527,3317
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,3527,2706

# map

In [87]:
df['origin'].unique()

<StringArray>
['Japan', 'US', 'India', 'Germany']
Length: 4, dtype: str

In [88]:
df['origin_map']=df['origin'].map({
    'US':1,
    'Japan':2,
    'India':3,
    'Germany':4
    
})
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,MaxWeight,origin_Max_weight,origin_map
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,3527,3374,2
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,3527,2706,1
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,3527,3527,3
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,3527,3317,4
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,3527,2706,1

# Lambda

In [93]:
a=[1,2,30,50,45]
b=[20,40,60,25,30]
c=[11,22,33,44,55]
df=pd.DataFrame(zip(a,b,c))
df.columns=['val1','val2','val3']
df

   val1  val2  val3
0     1    20    11
1     2    40    22
2    30    60    33
3    50    25    44
4    45    30    55

In [94]:
def do_sqr(x):
    return x**2

In [95]:
df.apply(do_sqr)

   val1  val2  val3
0     1   400   121
1     4  1600   484
2   900  3600  1089
3  2500   625  1936
4  2025   900  3025

In [96]:
df.apply(lambda x: x**2)

   val1  val2  val3
0     1   400   121
1     4  1600   484
2   900  3600  1089
3  2500   625  1936
4  2025   900  3025

# pipe Function
- series/continuos operation
- 1 step then 2nd step ...

In [108]:
def convert_to_kw(hp):
    return hp*0.745

def fix_decimals(value):
    return round(value,2)

In [109]:
# transform HOrsepower to kilowatts and fix Decimal

In [110]:
df=pd.read_csv('../../../car_data_500.csv').head()

In [111]:
df['Kilowatts']=df['Horsepower'].apply(convert_to_kw)

In [112]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,Kilowatts
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,184.015
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,138.570
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,197.425
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,146.020
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,104.300

In [113]:
df['kkkwww']=df['Kilowatts'].apply(fix_decimals)

In [114]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,Kilowatts,kkkwww
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,184.015,184.01
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,138.570,138.57
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,197.425,197.43
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,146.020,146.02
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,104.300,104.30

In [115]:
df['pipe_kw_dec']=df['Horsepower'].pipe(convert_to_kw).pipe(fix_decimals)

In [116]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,Kilowatts,kkkwww,pipe_kw_dec
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,184.015,184.01,184.02
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,138.570,138.57,138.57
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,197.425,197.43,197.42
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,146.020,146.02,146.02
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,104.300,104.30,104.30