In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../../../car_data_500.csv").head(10)

In [3]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US
5,Kia,15.7,6.0,2659,155,3156,10.2,76,US
6,Toyota,16.9,8.0,3148,102,3974,15.5,79,South Korea
7,Ford,19.1,8.0,4693,150,1800,12.7,72,South Korea
8,BMW,17.5,6.0,3801,221,1818,10.8,76,South Korea
9,Tata,18.1,6.0,3268,130,2383,11.1,80,India

# get Value Based on index and Column

In [4]:
df.at[3,'origin']

'Germany'

In [5]:
df.at[3,'car']

'Hyundai'

In [6]:
df.at[7,'Displacement']

np.int64(4693)

In [7]:
df.iat[2,4]

np.int64(265)

In [10]:
df.iat[2,4]=555

In [11]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,555,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US
5,Kia,15.7,6.0,2659,155,3156,10.2,76,US
6,Toyota,16.9,8.0,3148,102,3974,15.5,79,South Korea
7,Ford,19.1,8.0,4693,150,1800,12.7,72,South Korea
8,BMW,17.5,6.0,3801,221,1818,10.8,76,South Korea
9,Tata,18.1,6.0,3268,130,2383,11.1,80,India

In [12]:
df.loc[6,'car']

'Toyota'

In [13]:
df.iloc[6,0]

'Toyota'

In [14]:
df.loc[6].at['car']

'Toyota'

# Rows

In [16]:
df.loc[3]

car             Hyundai
MPO                11.5
Cylinder            6.0
Displacement       4498
Horsepower          196
weight             3317
Accelarate          9.9
Model                77
origin          Germany
Name: 3, dtype: object

In [20]:
df.loc[3]=["hyndaaaaaai",12,7.0,5544,200,3317,8.5,55,'germany']

In [21]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,555,3527,8.3,80,India
3,hyndaaaaaai,12.0,7.0,5544,200,3317,8.5,55,germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US
5,Kia,15.7,6.0,2659,155,3156,10.2,76,US
6,Toyota,16.9,8.0,3148,102,3974,15.5,79,South Korea
7,Ford,19.1,8.0,4693,150,1800,12.7,72,South Korea
8,BMW,17.5,6.0,3801,221,1818,10.8,76,South Korea
9,Tata,18.1,6.0,3268,130,2383,11.1,80,India

In [17]:
df.loc[3:6]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US
5,Kia,15.7,6.0,2659,155,3156,10.2,76,US
6,Toyota,16.9,8.0,3148,102,3974,15.5,79,South Korea

In [18]:
df.loc[[1,3,5,7,9]]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
5,Kia,15.7,6.0,2659,155,3156,10.2,76,US
7,Ford,19.1,8.0,4693,150,1800,12.7,72,South Korea
9,Tata,18.1,6.0,3268,130,2383,11.1,80,India

# Columns

In [22]:
df.loc[:,'car']

0           Ford
1         Jaguar
2           Audi
3    hyndaaaaaai
4           Tata
5            Kia
6         Toyota
7           Ford
8            BMW
9           Tata
Name: car, dtype: str

In [23]:
df.loc[:,'Displacement']

0    1823
1    1793
2    1943
3    5544
4    2968
5    2659
6    3148
7    4693
8    3801
9    3268
Name: Displacement, dtype: int64

In [24]:
df.loc[:,'car':'Displacement']

           car   MPO  Cylinder  Displacement
0         Ford  20.7       6.0          1823
1       Jaguar  17.4       4.0          1793
2         Audi  21.3       8.0          1943
3  hyndaaaaaai  12.0       7.0          5544
4         Tata  18.0       6.0          2968
5          Kia  15.7       6.0          2659
6       Toyota  16.9       8.0          3148
7         Ford  19.1       8.0          4693
8          BMW  17.5       6.0          3801
9         Tata  18.1       6.0          3268

In [25]:
df.loc[:,['car','Displacement']]

           car  Displacement
0         Ford          1823
1       Jaguar          1793
2         Audi          1943
3  hyndaaaaaai          5544
4         Tata          2968
5          Kia          2659
6       Toyota          3148
7         Ford          4693
8          BMW          3801
9         Tata          3268

In [26]:
df.loc[1:3,['car','Displacement']]

           car  Displacement
1       Jaguar          1793
2         Audi          1943
3  hyndaaaaaai          5544

In [27]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,555,3527,8.3,80,India
3,hyndaaaaaai,12.0,7.0,5544,200,3317,8.5,55,germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US
5,Kia,15.7,6.0,2659,155,3156,10.2,76,US
6,Toyota,16.9,8.0,3148,102,3974,15.5,79,South Korea
7,Ford,19.1,8.0,4693,150,1800,12.7,72,South Korea
8,BMW,17.5,6.0,3801,221,1818,10.8,76,South Korea
9,Tata,18.1,6.0,3268,130,2383,11.1,80,India

In [29]:
df.add_prefix("item_",axis=1)

,item_car,item_MPO,item_Cylinder,item_Displacement,item_Horsepower,item_weight,item_Accelarate,item_Model,item_origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,555,3527,8.3,80,India
3,hyndaaaaaai,12.0,7.0,5544,200,3317,8.5,55,germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US
5,Kia,15.7,6.0,2659,155,3156,10.2,76,US
6,Toyota,16.9,8.0,3148,102,3974,15.5,79,South Korea
7,Ford,19.1,8.0,4693,150,1800,12.7,72,South Korea
8,BMW,17.5,6.0,3801,221,1818,10.8,76,South Korea
9,Tata,18.1,6.0,3268,130,2383,11.1,80,India

In [30]:
df.add_prefix("item_",axis=0)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
item_0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
item_1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
item_2,Audi,21.3,8.0,1943,555,3527,8.3,80,India
item_3,hyndaaaaaai,12.0,7.0,5544,200,3317,8.5,55,germany
item_4,Tata,18.0,6.0,2968,140,2706,7.2,74,US
item_5,Kia,15.7,6.0,2659,155,3156,10.2,76,US
item_6,Toyota,16.9,8.0,3148,102,3974,15.5,79,South Korea
item_7,Ford,19.1,8.0,4693,150,1800,12.7,72,South Korea
item_8,BMW,17.5,6.0,3801,221,1818,10.8,76,South Korea
item_9,Tata,18.1,6.0,3268,130,2383,11.1,80,India

In [31]:
df.add_suffix("_item",axis=0)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0_item,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1_item,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2_item,Audi,21.3,8.0,1943,555,3527,8.3,80,India
3_item,hyndaaaaaai,12.0,7.0,5544,200,3317,8.5,55,germany
4_item,Tata,18.0,6.0,2968,140,2706,7.2,74,US
5_item,Kia,15.7,6.0,2659,155,3156,10.2,76,US
6_item,Toyota,16.9,8.0,3148,102,3974,15.5,79,South Korea
7_item,Ford,19.1,8.0,4693,150,1800,12.7,72,South Korea
8_item,BMW,17.5,6.0,3801,221,1818,10.8,76,South Korea
9_item,Tata,18.1,6.0,3268,130,2383,11.1,80,India

In [32]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,555,3527,8.3,80,India
3,hyndaaaaaai,12.0,7.0,5544,200,3317,8.5,55,germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US
5,Kia,15.7,6.0,2659,155,3156,10.2,76,US
6,Toyota,16.9,8.0,3148,102,3974,15.5,79,South Korea
7,Ford,19.1,8.0,4693,150,1800,12.7,72,South Korea
8,BMW,17.5,6.0,3801,221,1818,10.8,76,South Korea
9,Tata,18.1,6.0,3268,130,2383,11.1,80,India

In [34]:
df['Cylinder'].idxmax()

2

In [35]:
df['Cylinder'].idxmin()

1

In [36]:
df['Cylinder'].argmax()

np.int64(2)

In [37]:
df['Cylinder'].argmin()

np.int64(1)

In [38]:
df['Cylinder'].max()

np.float64(8.0)

In [39]:
df['Cylinder'].min()

np.float64(4.0)