In [5]:
import pandas as pd

In [2]:
df_courses=pd.DataFrame([['22C01','C#',6000],['22C02','C++',9000],['22C03','Dart',6000],['22C04','Flutter',18000],['22C05','java',6000]])
df_courses.columns=["ID","Name","fee"]
df_courses

      ID     Name    fee
0  22C01       C#   6000
1  22C02      C++   9000
2  22C03     Dart   6000
3  22C04  Flutter  18000
4  22C05     java   6000

In [3]:
df_payment=pd.DataFrame([['22C001','2022-01-02','22S001','22C15',1000],['22C002','2022-01-02','22S001','22C12',8000],['22C003','2022-01-09','22S002','22C02',1000],['22C004','2022-01-09','22S002','22C03',7000],['22C005','2022-01-09','22S002','22C02',5000]])
df_payment.columns=['Transaction','Data','Student','Course','Paid']
df_payment

  Transaction        Data Student Course  Paid
0      22C001  2022-01-02  22S001  22C15  1000
1      22C002  2022-01-02  22S001  22C12  8000
2      22C003  2022-01-09  22S002  22C02  1000
3      22C004  2022-01-09  22S002  22C03  7000
4      22C005  2022-01-09  22S002  22C02  5000

In [ ]:
# Like Sql join
#df_courses.merge(df_payment,how="left",left_on='ID',right_on='Course')

In [6]:
df_courses.merge(df_payment,how="left",left_on='ID',right_on='Course')

      ID     Name    fee Transaction        Data Student Course    Paid
0  22C01       C#   6000         NaN         NaN     NaN    NaN     NaN
1  22C02      C++   9000      22C003  2022-01-09  22S002  22C02  1000.0
2  22C02      C++   9000      22C005  2022-01-09  22S002  22C02  5000.0
3  22C03     Dart   6000      22C004  2022-01-09  22S002  22C03  7000.0
4  22C04  Flutter  18000         NaN         NaN     NaN    NaN     NaN
5  22C05     java   6000         NaN         NaN     NaN    NaN     NaN

In [7]:
# select * from main_table as m join join_table as j on m.id=j_course_id

In [8]:
df_courses.merge(df_payment,how="right",left_on='ID',right_on='Course')

      ID  Name     fee Transaction        Data Student Course  Paid
0    NaN   NaN     NaN      22C001  2022-01-02  22S001  22C15  1000
1    NaN   NaN     NaN      22C002  2022-01-02  22S001  22C12  8000
2  22C02   C++  9000.0      22C003  2022-01-09  22S002  22C02  1000
3  22C03  Dart  6000.0      22C004  2022-01-09  22S002  22C03  7000
4  22C02   C++  9000.0      22C005  2022-01-09  22S002  22C02  5000

In [9]:
df_courses.merge(df_payment,how="inner",left_on='ID',right_on='Course')

      ID  Name   fee Transaction        Data Student Course  Paid
0  22C02   C++  9000      22C003  2022-01-09  22S002  22C02  1000
1  22C02   C++  9000      22C005  2022-01-09  22S002  22C02  5000
2  22C03  Dart  6000      22C004  2022-01-09  22S002  22C03  7000