In [3]:
import pandas as pd

In [30]:
df=pd.read_csv('../../../pandas_50_records.csv')
df=df.head()

Check Null Value
1. df.isna() # true if null value Present
2. df.isna().sum() #Based on Columnwise
3. df.isnull()
4. df.isnull().sum()
5. df.loc[df['Horsepower'].isna()]

In [7]:
df.isna()

      ID   Name    Age  Course  Marks   City
0  False  False  False   False  False  False
1  False  False  False   False  False  False
2  False  False  False   False  False  False
3  False  False   True   False  False  False
4  False  False  False   False  False  False

In [8]:
df.isna().sum()

ID        0
Name      0
Age       1
Course    0
Marks     0
City      0
dtype: int64

In [9]:
df.isnull()

      ID   Name    Age  Course  Marks   City
0  False  False  False   False  False  False
1  False  False  False   False  False  False
2  False  False  False   False  False  False
3  False  False   True   False  False  False
4  False  False  False   False  False  False

In [10]:
df.isnull().sum()

ID        0
Name      0
Age       1
Course    0
Marks     0
City      0
dtype: int64

In [14]:
df['Age'].isnull()

0    False
1    False
2    False
3     True
4    False
Name: Age, dtype: bool

In [15]:
df.loc[df['Age'].isnull()]

   ID       Name  Age    Course  Marks     City
3   4  Student_4  NaN  Power BI   78.0  Chennai

In [16]:
df.loc[~ df['Age'].isnull()]

   ID       Name   Age  Course  Marks     City
0   1  Student_1  24.0     SQL   62.0    Salem
1   2  Student_2  21.0  Pandas   70.0    Salem
2   3  Student_3  22.0     SQL   88.0  Madurai
4   5  Student_5  20.0     SQL   54.0    Salem

- Drop Null Value row
- df.dropna()
- df.fillna(1000)
- df.dropna(how="all")
- df.dropna(how="any")
- df.dropna(subset=["Age"])
- df.dropna(thresh=6)

In [31]:
df

   ID       Name   Age    Course  Marks     City
0   1  Student_1  24.0       SQL   62.0    Salem
1   2  Student_2  21.0    Pandas   70.0    Salem
2   3  Student_3  22.0       SQL   88.0  Madurai
3   4  Student_4   NaN  Power BI   78.0  Chennai
4   5  Student_5  20.0       SQL   54.0    Salem

In [32]:
df.shape

(5, 6)

In [33]:
df.dropna()

   ID       Name   Age  Course  Marks     City
0   1  Student_1  24.0     SQL   62.0    Salem
1   2  Student_2  21.0  Pandas   70.0    Salem
2   3  Student_3  22.0     SQL   88.0  Madurai
4   5  Student_5  20.0     SQL   54.0    Salem

In [34]:
df.dropna().shape

(4, 6)

In [35]:
df['City'].dropna()

0      Salem
1      Salem
2    Madurai
3    Chennai
4      Salem
Name: City, dtype: str

In [36]:
df.dropna(how="all")

   ID       Name   Age    Course  Marks     City
0   1  Student_1  24.0       SQL   62.0    Salem
1   2  Student_2  21.0    Pandas   70.0    Salem
2   3  Student_3  22.0       SQL   88.0  Madurai
3   4  Student_4   NaN  Power BI   78.0  Chennai
4   5  Student_5  20.0       SQL   54.0    Salem

In [37]:
df.dropna(how="any")

   ID       Name   Age  Course  Marks     City
0   1  Student_1  24.0     SQL   62.0    Salem
1   2  Student_2  21.0  Pandas   70.0    Salem
2   3  Student_3  22.0     SQL   88.0  Madurai
4   5  Student_5  20.0     SQL   54.0    Salem

In [38]:
df.dropna(thresh=4)

   ID       Name   Age    Course  Marks     City
0   1  Student_1  24.0       SQL   62.0    Salem
1   2  Student_2  21.0    Pandas   70.0    Salem
2   3  Student_3  22.0       SQL   88.0  Madurai
3   4  Student_4   NaN  Power BI   78.0  Chennai
4   5  Student_5  20.0       SQL   54.0    Salem

In [39]:
df.dropna(thresh=6)

   ID       Name   Age  Course  Marks     City
0   1  Student_1  24.0     SQL   62.0    Salem
1   2  Student_2  21.0  Pandas   70.0    Salem
2   3  Student_3  22.0     SQL   88.0  Madurai
4   5  Student_5  20.0     SQL   54.0    Salem

In [40]:
 df.fillna(1000)

   ID       Name     Age    Course  Marks     City
0   1  Student_1    24.0       SQL   62.0    Salem
1   2  Student_2    21.0    Pandas   70.0    Salem
2   3  Student_3    22.0       SQL   88.0  Madurai
3   4  Student_4  1000.0  Power BI   78.0  Chennai
4   5  Student_5    20.0       SQL   54.0    Salem