In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../../../car_data_500.csv").head()
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

# access Cell

In [5]:
df.at[0,'car']

'Ford'

In [6]:
df.at[2,'Displacement']

np.int64(1943)

In [7]:
df.at[3,'origin']

'Germany'

In [8]:
df.iat[0,0]

'Ford'

In [9]:
df.loc[3,'car']

'Hyundai'

In [10]:
df.iloc[3,3]

np.int64(4498)

In [11]:
df.loc[3].at['car']

'Hyundai'

# access Row

In [13]:
df.loc[0]

car              Ford
MPO              20.7
Cylinder          6.0
Displacement     1823
Horsepower        247
weight           3374
Accelarate       15.5
Model              76
origin          Japan
Name: 0, dtype: object

In [14]:
df.loc[1:3]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany

In [16]:
df.loc[[1,2,4]]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

# access column

In [17]:
df.loc[:,'car']

0       Ford
1     Jaguar
2       Audi
3    Hyundai
4       Tata
Name: car, dtype: str

In [18]:
df.loc[:,'origin']='US'

In [19]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,US
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,US
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,US
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [22]:
df.loc[:,'Model']=range(0,5)
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,0,US
1,Jaguar,17.4,4.0,1793,186,2196,15.9,1,US
2,Audi,21.3,8.0,1943,265,3527,8.3,2,US
3,Hyundai,11.5,6.0,4498,196,3317,9.9,3,US
4,Tata,18.0,6.0,2968,140,2706,7.2,4,US