In [1]:
import pandas as pd

In [5]:
fruits=['Apple','Orange','Banana']
Color=['Red','orange','Yellow']
price=[100,200,300]
basket=zip(fruits,Color,price)
df=pd.DataFrame(basket)
df.columns=["Fruits","Color","Price"]
df

   Fruits   Color  Price
0   Apple     Red    100
1  Orange  orange    200
2  Banana  Yellow    300

In [6]:
df.to_csv()

',Fruits,Color,Price\r\n0,Apple,Red,100\r\n1,Orange,orange,200\r\n2,Banana,Yellow,300\r\n'

In [8]:
df.to_csv("sample1")

In [9]:
df.to_excel("sample3.xlsx")

ModuleNotFoundError: No module named 'openpyxl'

In [15]:
df=pd.read_csv('sample.csv')
df

   Unnamed: 0  Fruits   Color  Price
0           0   Apple     Red    100
1           1  Orange  orange    200
2           2  Banana  Yellow    300

In [16]:
df['Fruits']

0     Apple
1    Orange
2    Banana
Name: Fruits, dtype: str

In [17]:
df.Color

0       Red
1    orange
2    Yellow
Name: Color, dtype: str

In [18]:
df.get("Price")

0    100
1    200
2    300
Name: Price, dtype: int64

In [20]:
df[['Fruits','Price']]

   Fruits  Price
0   Apple    100
1  Orange    200
2  Banana    300

In [21]:
df.get(["Price","Color"])

   Price   Color
0    100     Red
1    200  orange
2    300  Yellow

In [22]:
df

   Unnamed: 0  Fruits   Color  Price
0           0   Apple     Red    100
1           1  Orange  orange    200
2           2  Banana  Yellow    300

In [23]:
a=[1,2,3,4]
b=a
b.append(5)
print(a)

[1, 2, 3, 4, 5]

In [24]:
a=[2,3,4,5]
b=a.copy()
b.append(7)
print(a)

[2, 3, 4, 5]

In [25]:
df_new=df
df_new

   Unnamed: 0  Fruits   Color  Price
0           0   Apple     Red    100
1           1  Orange  orange    200
2           2  Banana  Yellow    300

In [27]:
df_new.columns=["Index","fruit","c","P"]
df_new

   Index   fruit       c    P
0      0   Apple     Red  100
1      1  Orange  orange  200
2      2  Banana  Yellow  300

In [28]:
df

   Index   fruit       c    P
0      0   Apple     Red  100
1      1  Orange  orange  200
2      2  Banana  Yellow  300

In [31]:
df_copy=df.copy()
df_copy.columns=["idx","Fruits","Color","Price"]
df_copy

   idx  Fruits   Color  Price
0    0   Apple     Red    100
1    1  Orange  orange    200
2    2  Banana  Yellow    300

In [32]:
df

   Index   fruit       c    P
0      0   Apple     Red  100
1      1  Orange  orange  200
2      2  Banana  Yellow  300

In [48]:
df=pd.read_csv('../../../data.csv')
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [49]:
df.head()

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [51]:
df.head()
df.reindex([4,2,0])

   Duration  Pulse  Maxpulse  Calories
4        45    117       148     406.0
2        60    103       135     340.0
0        60    110       130     409.1

In [41]:
df.tail()

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [45]:
df=df.set_index('Duration')

In [46]:
df

          Pulse  Maxpulse  Calories
Duration
60          110       130     409.1
60          117       145     479.0
60          103       135     340.0
45          109       175     282.4
45          117       148     406.0
...         ...       ...       ...
60          105       140     290.8
60          110       145     300.0
60          115       145     310.2
75          120       150     320.4
75          125       150     330.4

[169 rows x 3 columns]

In [52]:
df.reset_index()

     index  Duration  Pulse  Maxpulse  Calories
0        0        60    110       130     409.1
1        1        60    117       145     479.0
2        2        60    103       135     340.0
3        3        45    109       175     282.4
4        4        45    117       148     406.0
..     ...       ...    ...       ...       ...
164    164        60    105       140     290.8
165    165        60    110       145     300.0
166    166        60    115       145     310.2
167    167        75    120       150     320.4
168    168        75    125       150     330.4

[169 rows x 5 columns]

In [53]:
df.reset_index(drop=True)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]