In [1]:
import pandas as pd

In [2]:
df=pd.DataFrame(
    [
        [10,20,30],
        [2,4,6],
        [5,7,8]
    ]
)
df

    0   1   2
0  10  20  30
1   2   4   6
2   5   7   8

# add

In [3]:
df+1

    0   1   2
0  11  21  31
1   3   5   7
2   6   8   9

In [4]:
df.add(1)

    0   1   2
0  11  21  31
1   3   5   7
2   6   8   9

#Sub

In [7]:
df-1

   0   1   2
0  9  19  29
1  1   3   5
2  4   6   7

In [8]:
df.sub(1)

   0   1   2
0  9  19  29
1  1   3   5
2  4   6   7

In [9]:
df.subtract(1)

   0   1   2
0  9  19  29
1  1   3   5
2  4   6   7

In [10]:
# mul

In [11]:
df*5

    0    1    2
0  50  100  150
1  10   20   30
2  25   35   40

In [12]:
df.mul(5)

    0    1    2
0  50  100  150
1  10   20   30
2  25   35   40

In [13]:
df.multiply(5)

    0    1    2
0  50  100  150
1  10   20   30
2  25   35   40

# division

In [14]:
df/2

     0     1     2
0  5.0  10.0  15.0
1  1.0   2.0   3.0
2  2.5   3.5   4.0

In [15]:
df.div(2)

     0     1     2
0  5.0  10.0  15.0
1  1.0   2.0   3.0
2  2.5   3.5   4.0

In [16]:
df.divide(2)

     0     1     2
0  5.0  10.0  15.0
1  1.0   2.0   3.0
2  2.5   3.5   4.0

In [17]:
#mod

In [18]:
df%3

   0  1  2
0  1  2  0
1  2  1  0
2  2  1  2

In [19]:
df.mod(3)

   0  1  2
0  1  2  0
1  2  1  0
2  2  1  2

# Floor Division

In [20]:
df//2

   0   1   2
0  5  10  15
1  1   2   3
2  2   3   4

In [21]:
df.floordiv(2)

   0   1   2
0  5  10  15
1  1   2   3
2  2   3   4

In [22]:
df

    0   1   2
0  10  20  30
1   2   4   6
2   5   7   8

In [23]:
df.columns=['A','B','C']
df

    A   B   C
0  10  20  30
1   2   4   6
2   5   7   8

In [24]:
df['A']

0    10
1     2
2     5
Name: A, dtype: int64

In [25]:
df['A']+2

0    12
1     4
2     7
Name: A, dtype: int64

In [27]:
df['A']+ df['B']

0    30
1     6
2    12
dtype: int64

In [28]:
df['D']=df['A']+ df['B']

In [29]:
df

    A   B   C   D
0  10  20  30  30
1   2   4   6   6
2   5   7   8  12

In [30]:
# matrix Multiplication

In [31]:
a=pd.DataFrame(
    [
        [1,2],
        [3,4]
    ]
)
a

   0  1
0  1  2
1  3  4

In [32]:
b=pd.DataFrame(
    [
        [5,6],
        [7,8]
    ]
)
b

   0  1
0  5  6
1  7  8

In [33]:
a.dot(b)

    0   1
0  19  22
1  43  50

In [36]:
df=pd.DataFrame(
    [
        [10,200],
        [2,300],
        [5,500]
    ]
)
df.columns=['qty','price']
df

   qty  price
0   10    200
1    2    300
2    5    500

In [37]:
df['Total']=df['qty']*df['price']

In [38]:
df

   qty  price  Total
0   10    200   2000
1    2    300    600
2    5    500   2500

In [42]:
df.eval("tot=qty*price",inplace=True)

In [43]:
df

   qty  price  Total   tot
0   10    200   2000  2000
1    2    300    600   600
2    5    500   2500  2500