In [1]:
import pandas as pd

In [2]:
df_sort=pd.read_csv('car_data_500.csv').head()
df_sort

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [6]:
df_sort.sort_index(axis=1)

,Accelarate,Cylinder,Displacement,Horsepower,MPO,Model,car,origin,weight
0,15.5,6.0,1823,247,20.7,76,Ford,Japan,3374
1,15.9,4.0,1793,186,17.4,73,Jaguar,US,2196
2,8.3,8.0,1943,265,21.3,80,Audi,India,3527
3,9.9,6.0,4498,196,11.5,77,Hyundai,Germany,3317
4,7.2,6.0,2968,140,18.0,74,Tata,US,2706

In [7]:
df_sort.sort_values(by="car")

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [8]:
df_sort.sort_values(by=["car",'origin'])

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [9]:
df_sort

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [11]:
df_sort.sort_values(by="car", ascending=False)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India

In [13]:
df_sort.sort_values(by="car", ascending=False,inplace=True)

In [14]:
df_sort

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India